version: 0.4.0.{build}

configuration: Release

before_build:
- cmd: nuget restore src\Screna.sln

build:
  project: src\Screna.sln
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal