version: 0.7.0.{build}

image: Visual Studio 2017

before_build:
  - nuget restore src\Screna.sln

build:
  project: src\Screna.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal