version: 0.5.0.{build}

configuration: Release

image: Visual Studio 2017

before_build:
  - nuget restore src\Screna.sln

build: off
  project: src\Screna.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal